In [2]:
import networkx as nx
import glob
import numpy as np
import matplotlib.pyplot as plt

Read data

In [3]:
path = 'ordered_128/Pe0/'

data_array = []
data_fis = []

# Read in the data
for fi in glob.glob(path + '/fi*'):
    # extract the density from the path name
    density, run = tuple(fi.split('/')[2].split('_'))
    density = float(density.split('fi')[1])
    print(density, run)
    trj = glob.glob(fi + '/Trj/xyz.dump.*')[-1]
    print(trj)
    data = np.loadtxt(trj, skiprows=9)
        
    
    data_array.append(data[:,[1,2]])
    data_fis.append(density)


0.708 8
ordered_128/Pe0/fi0.708_8/Trj/xyz.dump.86000000
0.722 7
ordered_128/Pe0/fi0.722_7/Trj/xyz.dump.86000000
0.702 6
ordered_128/Pe0/fi0.702_6/Trj/xyz.dump.86000000
0.732 1
ordered_128/Pe0/fi0.732_1/Trj/xyz.dump.40000000
0.704 8
ordered_128/Pe0/fi0.704_8/Trj/xyz.dump.86000000
0.729 1
ordered_128/Pe0/fi0.729_1/Trj/xyz.dump.40000000
0.704 6
ordered_128/Pe0/fi0.704_6/Trj/xyz.dump.86000000
0.706 8
ordered_128/Pe0/fi0.706_8/Trj/xyz.dump.86000000
0.7 6
ordered_128/Pe0/fi0.700_6/Trj/xyz.dump.86000000
0.724 8
ordered_128/Pe0/fi0.724_8/Trj/xyz.dump.86000000
0.72 1
ordered_128/Pe0/fi0.720_1/Trj/xyz.dump.270000000
0.712 7
ordered_128/Pe0/fi0.712_7/Trj/xyz.dump.86000000
0.716 8
ordered_128/Pe0/fi0.716_8/Trj/xyz.dump.86000000
0.714 8
ordered_128/Pe0/fi0.714_8/Trj/xyz.dump.86000000
0.718 8
ordered_128/Pe0/fi0.718_8/Trj/xyz.dump.86000000
0.712 8
ordered_128/Pe0/fi0.712_8/Trj/xyz.dump.86000000
0.72 8
ordered_128/Pe0/fi0.720_8/Trj/xyz.dump.86000000
0.736 1
ordered_128/Pe0/fi0.736_1/Trj/xyz.dump.4000

In [9]:
len(data_array)
print(data_array[3].shape)

(16384, 2)


In [10]:
def distance_matrix(data):
    ''' Create a distance matrix from a list of points'''
    #n = len(data)
    #dist = np.zeros((n,n))
    m, n = np.meshgrid(data, data)
    dist = np.sqrt(np.sum((m - n)**2, axis=-1))    
    return dist

def discretize_distance_matrix(distance_matrix):
    '''Discretize the distance matrix'''
    np.where(distance_matrix <= 1.5, 1, 0)
    return distance_matrix

In [6]:
plt.figure(figsize=(10,10))
for i,conf in enumerate(data_array):
    if i % 4 != 0:
        continue
    plt.subplot(8,8,i+1)
    dist = distance_matrix(conf)
    dist = discretize_distance_matrix(dist)
    #G = nx.from_numpy_matrix(dist)
    plt.imshow(dist, interpolation='nearest')
    plt.xlabel(data_fis[i])
plt.show()

: 

: 

In [11]:
index = 2
dist = distance_matrix(data_array[index])
dist = np.where(dist <= 1.5, 1, 0)

print(dist)

plt.figure(figsize=(5,5))
plt.imshow(dist, interpolation='nearest')
plt.show()

: 

: 

In [7]:
print(np.where(dist <= 1.5, 1, 0))

[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
